### ISSUE TITLE
Can not be used for Objective-C?

### ISSUE THREAD

**Issue by ghost** [bannzai/ResourceKit#6]
xcodeURL: file:///Users/allen/Desktop/xxx/xxx/PROJECT_FILE_PATHproject.pbxproj, target: GlobalRobot, errorInfo: file: /Users/hirose/develop/oss/ResourceKit/Sources/ResourceKitCore/Parser/ProjectResourceParser.swift, line: 18
missing write content
Command /bin/sh failed with exit code 3

Can not be used for Objective-C?

**Comment by bannzai** [comment]
Thanks!
Maybe I miss to release.
Please check [this](https://github.com/bannzai/ResourceKit/releases/tag/0.4.3)

**Comment by mdk-aza** [comment]
@bannzai 
pod installした際に0.4.2のバージョンしか落ちて来ないのですが、何か心当たりはありますでしょうか。

**Comment by mdk-aza** [comment]
また、以下の形で0.4.3をインストールしたのですが、同様のエラーが出ます。。
pod 'ResourceKit', :podspec => './ResourceKit/ResourceKit.podspec'

**Comment by bannzai** [comment]
@noimpslmtbrk

Oh...
[0.4.4](https://github.com/bannzai/ResourceKit/releases/tag/0.4.4) を先ほどリリースしました！
こちらで直っていると思います！

**Comment by mdk-aza** [comment]
早速のご対応ありがとうございます！！
ビルドできることは確認致しました。
ただ、Resource.generated.swiftを含めてビルドをすると、Resource.generated.swift内でコンパイルエラーが発生します。

Objective-Cのコードのものがコンパイルエラーの該当箇所になっていそうなのです。
UIViewやUIcollectionView、UITableViewCellが対象なのですが、こちらは特別に何かファイルに記述が必要でしょうか。
ライブラリを使っている箇所はimportするのはわかったのですが。。

**Comment by bannzai** [comment]
@noimpslmtbrk

お、本当ですか。。。
特別な記述は必要ない前提です。
できればコンパイルが起きているコードの例とエラーメッセージを教えて欲しいのですが、いかがですか？

**Comment by bannzai** [comment]
先ほど少し試したのですが
Objective-C の `Bridge-Header` を用意していない場合はコンパイルエラーになっちゃいますね
もしこれが原因なら全てのXibを持っている `UITableViewCell` や `UICollectionViewCell`を  `Bridge-Header` の方で `import` 宣言してあげるとコンパイルはうまくいくと思います

**Comment by mdk-aza** [comment]
@bannzai 
お忙しい中で何度もご返信いただき、ありがとうございます！！！！！
Objective-C の Bridge-Header をやっていないので、おそらくこちらな気がします。
これから対応してみます！！！！

**Comment by mdk-aza** [comment]
@bannzai 
こちら、無事```Resource.generated.swift```を含んだ状態でコンパイルできました！！
本当にありがとうございます。

今回のbannzaiさんのライブラリを使わせて頂いていることや、ご対応をみて、
自分もオープンソースにどんどん貢献していこうと思えました。

本当にありがとうございました！！

**Comment by bannzai** [comment]
そう言ってもらえてとても嬉しいです！
オープンソースの貢献素敵です
お互いに頑張っていきましょう！
